apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-collector
  template:
    metadata:
      labels:
        app: data-collector
    spec:
      containers:
      - name: data-collector
        image: fabio0027/hw3:data_collectorv1.0
        env:
        - name: DATABASE_URL
          value: "postgresql://Hw1:123ciao@database:5432/Hw1DB"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        ports:
        - containerPort: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: data-collector
spec:
  selector:
    app: data-collector
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
