global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'email-notifier'

receivers:
  - name: 'email-notifier'
    email_configs:
      - to: 'gallone.fa@gmail.com'
        from: 'progettiunict@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'progettiunict@gmail.com'
        auth_password: 'sznamzimewelchvq'


