global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    monitor: 'DSBD'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - "alertmanager:9093"
      

rule_files:
  - 'alert.rules'


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'

  - job_name: 'server'
    static_configs:
      - targets:
          - 'server:8000' 

  - job_name: 'data_collector'
    static_configs:
      - targets:
          - 'data_collector:8001'

  - job_name: 'alert_notifier_system'
    static_configs:
      - targets:
          - 'alert-notifier-system-service:8002'
