apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-system
  template:
    metadata:
      labels:
        app: alert-system
    spec:
      containers:
      - name: alert-system
        image: fabio0027/hw3:alert_systemv1.0
        env:
        - name: DATABASE_URL
          value: "postgresql://Hw1:123ciao@database:5432/Hw1DB"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
